const config = {
    DEFAULT_TICKER: "^GSPC",
    WATCHLIST: [
        "^GSPC", "^IXIC", "^DJI", "AAPL", "MSFT", "GOOGL", "AMZN", "AVGO", "NVDA", "META", "GC=F", "SI=F", "CL=F",
        "CRDO", "CRWV", "ALAB", "ARM", "AAOI", "MU", "MRVL", "RKLB", "ASTS", "ONDS", "PL", "VRT", "POET", "RMBS", "XNDU", "RDW", "FTC.L", "SNDK", "MRAM"
    ],
    TICKER_NAMES: {
        "^GSPC": "S&P 500",
        "^IXIC": "NASDAQ",
        "^DJI": "Dow Jones",
        "AAPL": "Apple",
        "MSFT": "Microsoft",
        "GOOGL": "Alphabet",
        "AMZN": "Amazon",
        "AVGO": "Broadcom",
        "NVDA": "NVIDIA",
        "META": "Meta",
        "GC=F": "Gold",
        "SI=F": "Silver",
        "CL=F": "Crude Oil",
        "CRDO": "Credo Technology Group Holding ",
        "CRWV": "CoreWeave, Inc.",
        "ALAB": "Astera Labs, Inc.",
        "ARM": "Arm Holdings plc",
        "AAOI": "Applied Optoelectronics, Inc.",
        "MU": "Micron Technology, Inc.",
        "MRVL": "Marvell Technology, Inc.",
        "RKLB": "Rocket Lab Corporation",
        "ASTS": "AST SpaceMobile, Inc.",
        "ONDS": "Ondas Inc",
        "PL": "Planet Labs PBC",
        "VRT": "Vertiv Holdings, LLC",
        "POET": "POET Technologies Inc.",
        "RMBS": "Rambus, Inc.",
        "XNDU": "Xanadu Quantum Technologies Lim",
        "RDW": "Redwire Corporation",
        "FTC.L": "FILTRONIC PLC ORD 0.1P",
        "SNDK": "Sandisk Corporation",
        "MRAM": "Everspin Technologies, Inc.",
        "VUAGL": "Vanguard S&P 500 Acc",
        "FLTR.L": "Flutter Entertainment",
        "RR.L": "Rolls-Royce Holdings",
        "DARK.L": "Darktrace PLC",
        "OCDO.L": "Ocado Group",
        "BATS.L": "British American Tobacco",
        "ULVR.L": "Unilever PLC",
        "CRNC": "Cerence Inc.",
        "SOUN": "SoundHound AI, Inc.",
        "ANET": "Arista Networks, Inc.",
        "LRCX": "Lam Research Corporation",
        "NU": "Nu Holdings Ltd. (Nubank)",
        "CLS": "Celestica Inc.",
        "APP": "AppLovin Corporation",
        "MOD": "Modine Manufacturing Co.",
        "MELI": "MercadoLibre, Inc.",
        "SE": "Sea Limited",
        "CELH": "Celsius Holdings, Inc.",
        "WISE.L": "Wise PLC",
        "DPLM.L": "Diploma PLC",
        "GAW.L": "Games Workshop Group PLC",
        "IHG.L": "InterContinental Hotels Group",
        "COHR": "Coherent Corp. (Photonics)",
        "LITE": "Lumentum Holdings Inc.",
        "VECO": "Veeco Instruments Inc.",
        "IPGP": "IPG Photonics Corp.",
        "FN": "Fabrinet (Optics)",
        "VIAV": "Viavi Solutions Inc.",
        "AEIS": "Advanced Energy Ind.",
        "IONQ": "IonQ, Inc. (Quantum)",
        "RGTI": "Rigetti Computing (Quantum)",
        "QBTS": "D-Wave Quantum Inc.",
        "QUBT": "Quantum Computing Inc.",
        "LUNR": "Intuitive Machines (Space)",
        "LLAP": "Terran Orbital (Space)",
        "SIDU": "Sidus Space, Inc.",
        "BBAI": "BigBear.ai (AI Defense)",
        "BKSY": "BlackSky Technology",
        "SPIR": "Spire Global, Inc.",
        "SERA.L": "Seraphim Space Trust",
        "ANET": "Arista Networks (AI/Cloud)",
        "KLAC": "KLA Corp. (Semis)",
        "ASML": "ASML Holding NV",
        "TER": "Teradyne (Robotics/AI)",
        "POWL": "Powell Industries (AI Power)",
        "CLS": "Celestica (AI Infrastructure)",
        "MOD": "Modine (AI Thermal)",
        "DARK.L": "Darktrace (AI Security)",
        "SGE.L": "Sage Group (AI ERP)",
    },
    DISCOVERY_LIST: [
        "COHR", "LITE", "VECO", "IPGP", "FN", "VIAV", "AEIS", "IONQ", "RGTI", "QBTS", "QUBT", "LUNR", "LLAP", "SIDU", "BBAI",
        "BKSY", "SPIR", "SERA.L", "ANET", "KLAC", "ASML", "TER", "POWL", "CLS", "MOD", "DARK.L", "SGE.L"
    ],
    HISTORY_PERIOD: "1y",
    HISTORY_INTERVAL: "1d",
    
    // Technical Indicator Settings
    RSI_PERIOD: 14,
    RSI_OVERBOUGHT: 70,
    RSI_OVERSOLD: 30,
    
    MACD_FAST: 12,
    MACD_SLOW: 26,
    MACD_SIGNAL: 9,
    
    BOLLINGER_PERIOD: 20,
    BOLLINGER_STD_DEV: 2,
    
    SMA_SHORT: 50,
    SMA_LONG: 200,
    EMA_SHORT: 12,
    EMA_LONG: 26,
    
    // News feeds
    NEWS_FEEDS: {
        "Bloomberg": "https://feeds.bloomberg.com/markets/news.rss",
        "Reuters Business": "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best",
        "CNBC Top News": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",
        "CNBC Finance": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664",
        "MarketWatch": "http://feeds.marketwatch.com/marketwatch/topstories/",
        "Yahoo Finance": "https://finance.yahoo.com/news/rssindex",
        "Investing.com": "https://www.investing.com/rss/news.rss",
        "Financial Times": "https://www.ft.com/rss/home",
    },
    MAX_ARTICLES_PER_SOURCE: 15,
    
    // Weightings
    SIGNAL_WEIGHTS: {
        sentiment: 0.20,
        rsi: 0.15,
        macd: 0.15,
        moving_avg: 0.25,
        bollinger: 0.15,
        volume: 0.10,
    },
    
    PREDICTION_THRESHOLDS: {
        STRONG_BULL: 0.5,
        BULL: 0.15,
        NEUTRAL_HIGH: 0.15,
        NEUTRAL_LOW: -0.15,
        BEAR: -0.5,
    },
    
    DIP_DROP_THRESHOLD: -0.02,
    DIP_RSI_THRESHOLD: 35,
    DIP_LOOKBACK_DAYS: 5
};

module.exports = config;

